<?php

namespace App\Services;

/**
 * Master catalog of all available ledger accounts, with per-category
 * relevance metadata (core / suggested / available / hidden).
 *
 * Used by onboarding Step 3 to let users pick which accounts to seed,
 * and by the DefaultLedgerAccountsSeeder to filter accounts.
 *
 * Categories: trading, manufacturing, service, hybrid
 *  - core_for:      Account is mandatory (locked checkbox, always seeded)
 *  - suggested_for: Pre-checked but user can remove
 *  - categories:    Which categories can see this account at all
 *                   (omitted = hidden for that category)
 */
class LedgerAccountCatalog
{
    /**
     * Get all available accounts for a business category,
     * grouped by account group, with selection state flags.
     */
    public static function getForCategory(string $category): array
    {
        return collect(static::MASTER_CATALOG)
            ->filter(fn($a) => in_array($category, $a['categories']))
            ->groupBy('group')
            ->map(function ($accounts, $group) use ($category) {
                return $accounts->map(function ($account) use ($category) {
                    return [
                        'code'         => $account['code'],
                        'name'         => $account['name'],
                        'description'  => $account['description'],
                        'group'        => $account['group'],
                        'type'         => $account['type'],
                        'is_core'      => in_array($category, $account['core_for'] ?? []),
                        'is_suggested' => in_array($category, $account['suggested_for'] ?? []),
                        'is_system'    => $account['is_system'] ?? false,
                    ];
                })->values()->toArray();
            })
            ->toArray();
    }

    /**
     * Get default selected account codes for a category
     * (core + suggested, but not merely "available").
     */
    public static function getDefaultSelection(string $category): array
    {
        return collect(static::MASTER_CATALOG)
            ->filter(function ($account) use ($category) {
                if (!in_array($category, $account['categories'])) return false;
                return in_array($category, $account['core_for'] ?? [])
                    || in_array($category, $account['suggested_for'] ?? []);
            })
            ->pluck('code')
            ->values()
            ->toArray();
    }

    /**
     * Get core (mandatory) account codes for a category.
     */
    public static function getCoreAccounts(string $category): array
    {
        return collect(static::MASTER_CATALOG)
            ->filter(fn($a) => in_array($category, $a['core_for'] ?? []))
            ->pluck('code')
            ->values()
            ->toArray();
    }

    /**
     * Validate user selection — ensure all core accounts are included.
     */
    public static function validateSelection(string $category, array $selectedCodes): array
    {
        $coreCodes = static::getCoreAccounts($category);
        return array_values(array_unique(array_merge($coreCodes, $selectedCodes)));
    }

    /**
     * Get the full account data for a set of codes (for seeding).
     */
    public static function getAccountsByCode(array $codes): array
    {
        return collect(static::MASTER_CATALOG)
            ->filter(fn($a) => in_array($a['code'], $codes))
            ->values()
            ->toArray();
    }

    // ─── Master Account Catalog ───────────────────────────────
    // Each entry mirrors the DefaultLedgerAccountsSeeder but adds
    // category-awareness (categories, core_for, suggested_for).
    //
    // Abbreviations for the 4 categories:
    //   T = trading, M = manufacturing, S = service, H = hybrid
    //   ALL = [T, M, S, H]

    public const MASTER_CATALOG = [

        // ──────────────── CURRENT ASSETS ────────────────────────
        [
            'code'          => 'CASH-001',
            'name'          => 'Cash in Hand',
            'description'   => 'Physical cash available in the business',
            'group'         => 'Current Assets',
            'type'          => 'asset',
            'is_system'     => true,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => ['trading', 'manufacturing', 'service', 'hybrid'],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'PETTY-001',
            'name'          => 'Petty Cash',
            'description'   => 'Small cash fund for minor expenses',
            'group'         => 'Current Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'ST-INV-001',
            'name'          => 'Short-term Investments',
            'description'   => 'Short-term investments',
            'group'         => 'Current Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'PREPAID-EXP-001',
            'name'          => 'Prepaid Expenses',
            'description'   => 'Expenses paid in advance (Rent, Insurance)',
            'group'         => 'Current Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'ACCRUED-INC-001',
            'name'          => 'Accrued Income',
            'description'   => 'Income earned but not yet received',
            'group'         => 'Current Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['service', 'hybrid'],
        ],
        [
            'code'          => 'FIXED-DEP-001',
            'name'          => 'Fixed Deposits',
            'description'   => 'Funds held in fixed deposits',
            'group'         => 'Current Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'INV-001',
            'name'          => 'Inventory',
            'description'   => 'Goods available for sale (Raw Materials, WIP, Finished Goods)',
            'group'         => 'Current Assets',
            'type'          => 'asset',
            'is_system'     => true,
            'categories'    => ['trading', 'manufacturing', 'hybrid'],
            'core_for'      => ['trading', 'manufacturing', 'hybrid'],
            'suggested_for' => ['trading', 'manufacturing', 'hybrid'],
        ],
        [
            'code'          => 'AR-001',
            'name'          => 'Accounts Receivable',
            'description'   => 'Money owed by customers — Debtors',
            'group'         => 'Current Assets',
            'type'          => 'asset',
            'is_system'     => true,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => ['trading', 'manufacturing', 'service', 'hybrid'],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'SALES-LED-001',
            'name'          => 'Sales Ledger',
            'description'   => 'Customer receivables ledger',
            'group'         => 'Current Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'hybrid'],
        ],
        [
            'code'          => 'STOCK-001',
            'name'          => 'Stock in Hand',
            'description'   => 'Inventory / Stock on hand',
            'group'         => 'Current Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'hybrid'],
        ],
        [
            'code'          => 'VAT-IN-001',
            'name'          => 'VAT Input',
            'description'   => 'VAT paid to suppliers',
            'group'         => 'Current Assets',
            'type'          => 'asset',
            'is_system'     => true,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => ['trading', 'manufacturing', 'service', 'hybrid'],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'PAYE-REC-001',
            'name'          => 'PAYE Tax Receivable',
            'description'   => 'Pay As You Earn tax receivable from employees',
            'group'         => 'Current Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'WHT-REC-001',
            'name'          => 'Withholding Tax Receivable',
            'description'   => 'Withholding tax receivable from FIRS',
            'group'         => 'Current Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],

        // ──────────────── FIXED ASSETS ──────────────────────────
        [
            'code'          => 'FIXED-001',
            'name'          => 'Fixed Assets',
            'description'   => 'Tangible fixed assets (Property, Plant, Equipment)',
            'group'         => 'Fixed Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'hybrid'],
        ],
        [
            'code'          => 'ACCUM-DEPR-001',
            'name'          => 'Accumulated Depreciation',
            'description'   => 'Accumulated depreciation on fixed assets',
            'group'         => 'Fixed Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'INTANG-001',
            'name'          => 'Intangible Assets',
            'description'   => 'Intangible assets (Patents, Trademarks)',
            'group'         => 'Fixed Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['service', 'hybrid'],
        ],
        [
            'code'          => 'LT-INV-001',
            'name'          => 'Long-term Investments',
            'description'   => 'Long-term investments in other companies',
            'group'         => 'Fixed Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'GOODWILL-001',
            'name'          => 'Goodwill',
            'description'   => 'Goodwill from business acquisitions',
            'group'         => 'Fixed Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'ADVANCE-SUP-001',
            'name'          => 'Advance Payments to Suppliers',
            'description'   => 'Advance payments made to suppliers',
            'group'         => 'Fixed Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'hybrid'],
        ],
        [
            'code'          => 'LAND-001',
            'name'          => 'Land',
            'description'   => 'Land owned by the business',
            'group'         => 'Fixed Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'BUILD-001',
            'name'          => 'Buildings',
            'description'   => 'Buildings owned by the business',
            'group'         => 'Fixed Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['manufacturing'],
        ],
        [
            'code'          => 'MACH-001',
            'name'          => 'Machinery',
            'description'   => 'Machinery owned by the business',
            'group'         => 'Fixed Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['manufacturing', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['manufacturing', 'hybrid'],
        ],
        [
            'code'          => 'VEH-001',
            'name'          => 'Vehicles',
            'description'   => 'Vehicles owned by the business',
            'group'         => 'Fixed Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing'],
        ],
        [
            'code'          => 'FURN-001',
            'name'          => 'Furniture & Fixtures',
            'description'   => 'Office furniture and fixtures',
            'group'         => 'Fixed Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'COMP-EQ-001',
            'name'          => 'Computer Equipment',
            'description'   => 'Computers and IT equipment',
            'group'         => 'Fixed Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['service', 'hybrid'],
        ],
        [
            'code'          => 'OFF-EQ-001',
            'name'          => 'Office Equipment',
            'description'   => 'Office equipment and tools',
            'group'         => 'Fixed Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['service', 'hybrid'],
        ],
        [
            'code'          => 'LEASEHOLD-IMP-001',
            'name'          => 'Leasehold Improvements',
            'description'   => 'Improvements made to leased property',
            'group'         => 'Fixed Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'PATENT-001',
            'name'          => 'Patents',
            'description'   => 'Patents owned by the business',
            'group'         => 'Fixed Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'TRADEMARK-001',
            'name'          => 'Trademarks',
            'description'   => 'Trademarks owned by the business',
            'group'         => 'Fixed Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'COPYRIGHT-001',
            'name'          => 'Copyrights',
            'description'   => 'Copyrights owned by the business',
            'group'         => 'Fixed Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'SOFT-LIC-001',
            'name'          => 'Software Licenses',
            'description'   => 'Software licenses owned by the business',
            'group'         => 'Fixed Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['service'],
        ],
        [
            'code'          => 'ACCUM-DEPR-FIXED-001',
            'name'          => 'Accumulated Depreciation - Fixed Assets',
            'description'   => 'Accumulated depreciation on fixed assets',
            'group'         => 'Fixed Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'hybrid'],
        ],
        [
            'code'          => 'LT-INVEST-001',
            'name'          => 'Long-term Investments',
            'description'   => 'Long-term investments in other companies',
            'group'         => 'Fixed Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'REAL-EST-INV-001',
            'name'          => 'Real Estate Investments',
            'description'   => 'Investments in real estate properties',
            'group'         => 'Fixed Assets',
            'type'          => 'asset',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],

        // ──────────────── CURRENT LIABILITIES ───────────────────
        [
            'code'          => 'AP-001',
            'name'          => 'Accounts Payable',
            'description'   => 'Money owed to suppliers — Creditors',
            'group'         => 'Current Liabilities',
            'type'          => 'liability',
            'is_system'     => true,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => ['trading', 'manufacturing', 'service', 'hybrid'],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'PURCH-LED-001',
            'name'          => 'Purchase Ledger',
            'description'   => 'Supplier payables ledger',
            'group'         => 'Current Liabilities',
            'type'          => 'liability',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'hybrid'],
        ],
        [
            'code'          => 'VAT-OUT-001',
            'name'          => 'VAT Output',
            'description'   => 'VAT collected from customers',
            'group'         => 'Current Liabilities',
            'type'          => 'liability',
            'is_system'     => true,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => ['trading', 'manufacturing', 'service', 'hybrid'],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'PAYE-001',
            'name'          => 'PAYE Tax Payable',
            'description'   => 'Pay As You Earn tax payable',
            'group'         => 'Current Liabilities',
            'type'          => 'liability',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'WHT-001',
            'name'          => 'Withholding Tax Payable',
            'description'   => 'Withholding tax payable to FIRS',
            'group'         => 'Current Liabilities',
            'type'          => 'liability',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'PENSION-PAY-001',
            'name'          => 'Pension Payable',
            'description'   => 'Employee pension deductions payable',
            'group'         => 'Current Liabilities',
            'type'          => 'liability',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'NHF-PAY-001',
            'name'          => 'NHF Payable',
            'description'   => 'National Housing Fund deductions payable',
            'group'         => 'Current Liabilities',
            'type'          => 'liability',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'NHIS-PAY-001',
            'name'          => 'NHIS Payable',
            'description'   => 'National Health Insurance Scheme deductions payable',
            'group'         => 'Current Liabilities',
            'type'          => 'liability',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'NSITF-PAY-001',
            'name'          => 'NSITF Payable',
            'description'   => 'NSITF contributions payable',
            'group'         => 'Current Liabilities',
            'type'          => 'liability',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'ITF-PAY-001',
            'name'          => 'ITF Payable',
            'description'   => 'Industrial Training Fund contributions payable',
            'group'         => 'Current Liabilities',
            'type'          => 'liability',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['manufacturing'],
        ],
        [
            'code'          => 'UN-REV-001',
            'name'          => 'Unearned Revenue',
            'description'   => 'Revenue received in advance',
            'group'         => 'Current Liabilities',
            'type'          => 'liability',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['service', 'hybrid'],
        ],
        [
            'code'          => 'DIV-PAY-001',
            'name'          => 'Dividends Payable',
            'description'   => 'Dividends declared but not paid',
            'group'         => 'Current Liabilities',
            'type'          => 'liability',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'ACCRUED-EXP-001',
            'name'          => 'Accrued Expenses',
            'description'   => 'Expenses incurred but not yet paid',
            'group'         => 'Current Liabilities',
            'type'          => 'liability',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'BANK-LOAN-ST-001',
            'name'          => 'Bank Loans - Short-term',
            'description'   => 'Short-term bank loans payable',
            'group'         => 'Current Liabilities',
            'type'          => 'liability',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'BANK-LOAN-CUR-001',
            'name'          => 'Bank Loans - Current',
            'description'   => 'Current portion of bank loans payable',
            'group'         => 'Current Liabilities',
            'type'          => 'liability',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'SHORT-TERM-LOAN-001',
            'name'          => 'Short-term Loans',
            'description'   => 'Short-term loans payable',
            'group'         => 'Current Liabilities',
            'type'          => 'liability',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'MORTGAGE-PAYABLE-001',
            'name'          => 'Mortgage Payable',
            'description'   => 'Mortgage payable',
            'group'         => 'Current Liabilities',
            'type'          => 'liability',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'DEFERRED-TAX-LIAB-001',
            'name'          => 'Deferred Tax Liabilities',
            'description'   => 'Deferred tax liabilities',
            'group'         => 'Current Liabilities',
            'type'          => 'liability',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'LEASE-OBLIG-001',
            'name'          => 'Lease Obligations',
            'description'   => 'Lease obligations payable',
            'group'         => 'Current Liabilities',
            'type'          => 'liability',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],

        // ──────────────── DIRECT INCOME ─────────────────────────
        [
            'code'          => 'SALES-001',
            'name'          => 'Sales Revenue',
            'description'   => 'Revenue from sales of goods',
            'group'         => 'Direct Income',
            'type'          => 'income',
            'is_system'     => true,
            'categories'    => ['trading', 'manufacturing', 'hybrid'],
            'core_for'      => ['trading', 'manufacturing', 'hybrid'],
            'suggested_for' => ['trading', 'manufacturing', 'hybrid'],
        ],
        [
            'code'          => 'SERV-001',
            'name'          => 'Service Income',
            'description'   => 'Income from services provided',
            'group'         => 'Direct Income',
            'type'          => 'income',
            'is_system'     => true,
            'categories'    => ['service', 'hybrid', 'trading', 'manufacturing'],
            'core_for'      => ['service', 'hybrid'],
            'suggested_for' => ['service', 'hybrid'],
        ],
        [
            'code'          => 'SALES-RET-001',
            'name'          => 'Sales Returns',
            'description'   => 'Returns and allowances on sales',
            'group'         => 'Direct Income',
            'type'          => 'income',
            'is_system'     => true,
            'categories'    => ['trading', 'manufacturing', 'hybrid'],
            'core_for'      => ['trading', 'manufacturing'],
            'suggested_for' => ['trading', 'manufacturing', 'hybrid'],
        ],
        [
            'code'          => 'COMM-INC-001',
            'name'          => 'Commission Income',
            'description'   => 'Commission earned from sales or services',
            'group'         => 'Direct Income',
            'type'          => 'income',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['service', 'hybrid'],
        ],
        [
            'code'          => 'RENT-INC-001',
            'name'          => 'Rental Income',
            'description'   => 'Income from renting out property or equipment',
            'group'         => 'Direct Income',
            'type'          => 'income',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'PROF-FEES-INC-001',
            'name'          => 'Professional Fees Income',
            'description'   => 'Income from professional services',
            'group'         => 'Direct Income',
            'type'          => 'income',
            'is_system'     => false,
            'categories'    => ['service', 'hybrid'],
            'core_for'      => ['service'],
            'suggested_for' => ['service', 'hybrid'],
        ],
        [
            'code'          => 'GAIN-ON-SALE-001',
            'name'          => 'Gain on Sale of Assets',
            'description'   => 'Profit from selling assets',
            'group'         => 'Direct Income',
            'type'          => 'income',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],

        // ──────────────── INDIRECT INCOME ───────────────────────
        [
            'code'          => 'INT-INC-001',
            'name'          => 'Interest Income',
            'description'   => 'Interest earned on bank deposits',
            'group'         => 'Indirect Income',
            'type'          => 'income',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'DISC-REC-001',
            'name'          => 'Discount Received',
            'description'   => 'Discounts received from suppliers',
            'group'         => 'Indirect Income',
            'type'          => 'income',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing'],
        ],
        [
            'code'          => 'OTHER-INC-001',
            'name'          => 'Other Income',
            'description'   => 'Miscellaneous income',
            'group'         => 'Indirect Income',
            'type'          => 'income',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'GRANT-INC-001',
            'name'          => 'Grant Income',
            'description'   => 'Income from grants and donor funding',
            'group'         => 'Indirect Income',
            'type'          => 'income',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'FOREX-GAIN-001',
            'name'          => 'Foreign Exchange Gain',
            'description'   => 'Gain from foreign currency transactions',
            'group'         => 'Indirect Income',
            'type'          => 'income',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'ROYALTY-INC-001',
            'name'          => 'Royalty Income',
            'description'   => 'Income from royalties or intellectual property',
            'group'         => 'Indirect Income',
            'type'          => 'income',
            'is_system'     => false,
            'categories'    => ['manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'MISC-INC-001',
            'name'          => 'Miscellaneous Income',
            'description'   => 'Other income not categorized elsewhere',
            'group'         => 'Indirect Income',
            'type'          => 'income',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],

        // ──────────────── DIRECT EXPENSES ───────────────────────
        [
            'code'          => 'PURCH-001',
            'name'          => 'Purchases',
            'description'   => 'Purchases of goods for resale',
            'group'         => 'Direct Expenses',
            'type'          => 'expense',
            'is_system'     => true,
            'categories'    => ['trading', 'manufacturing', 'hybrid'],
            'core_for'      => ['trading', 'manufacturing', 'hybrid'],
            'suggested_for' => ['trading', 'manufacturing', 'hybrid'],
        ],
        [
            'code'          => 'COGS-001',
            'name'          => 'Cost of Goods Sold',
            'description'   => 'Direct cost of goods sold',
            'group'         => 'Direct Expenses',
            'type'          => 'expense',
            'is_system'     => true,
            'categories'    => ['trading', 'manufacturing', 'hybrid'],
            'core_for'      => ['trading', 'manufacturing', 'hybrid'],
            'suggested_for' => ['trading', 'manufacturing', 'hybrid'],
        ],
        [
            'code'          => 'PURCH-RET-001',
            'name'          => 'Purchase Returns',
            'description'   => 'Returns to suppliers',
            'group'         => 'Direct Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'hybrid'],
        ],
        [
            'code'          => 'RAW-MAT-PURCH-001',
            'name'          => 'Raw Material Purchases',
            'description'   => 'Purchases of raw materials for production',
            'group'         => 'Direct Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['manufacturing', 'hybrid'],
            'core_for'      => ['manufacturing'],
            'suggested_for' => ['manufacturing', 'hybrid'],
        ],
        [
            'code'          => 'FACTORY-OVERHEAD-001',
            'name'          => 'Factory Overhead',
            'description'   => 'Indirect costs related to manufacturing',
            'group'         => 'Direct Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['manufacturing', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['manufacturing', 'hybrid'],
        ],
        [
            'code'          => 'PACKAGING-COSTS-001',
            'name'          => 'Packaging Costs',
            'description'   => 'Costs related to packaging products',
            'group'         => 'Direct Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['manufacturing'],
        ],
        [
            'code'          => 'SHIPPING-COSTS-001',
            'name'          => 'Shipping Costs',
            'description'   => 'Costs related to shipping products',
            'group'         => 'Direct Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'hybrid'],
        ],
        [
            'code'          => 'MANUFACTURING-EXP-001',
            'name'          => 'Manufacturing Expenses',
            'description'   => 'Expenses directly related to manufacturing',
            'group'         => 'Direct Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['manufacturing', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['manufacturing'],
        ],
        [
            'code'          => 'LABOR-COSTS-001',
            'name'          => 'Labor Costs',
            'description'   => 'Costs associated with labor',
            'group'         => 'Direct Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['manufacturing'],
        ],
        [
            'code'          => 'FREIGHT-COSTS-001',
            'name'          => 'Freight Costs',
            'description'   => 'Costs related to freight and transportation',
            'group'         => 'Direct Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading'],
        ],
        [
            'code'          => 'CUSTOMS-DUTIES-001',
            'name'          => 'Customs Duties',
            'description'   => 'Customs duties and tariffs on imported goods',
            'group'         => 'Direct Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],

        // ──────────────── INDIRECT EXPENSES ─────────────────────
        [
            'code'          => 'RENT-001',
            'name'          => 'Office Rent',
            'description'   => 'Monthly office rent expense',
            'group'         => 'Indirect Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'SAL-001',
            'name'          => 'Salaries & Wages',
            'description'   => 'Employee salaries and wages',
            'group'         => 'Indirect Expenses',
            'type'          => 'expense',
            'is_system'     => true,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => ['trading', 'manufacturing', 'service', 'hybrid'],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'ELEC-001',
            'name'          => 'Electricity Expense',
            'description'   => 'Electricity and power expenses',
            'group'         => 'Indirect Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'TEL-001',
            'name'          => 'Telephone & Internet',
            'description'   => 'Communication expenses',
            'group'         => 'Indirect Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['service', 'hybrid'],
        ],
        [
            'code'          => 'BANK-CHG-001',
            'name'          => 'Bank Charges',
            'description'   => 'Bank fees and charges',
            'group'         => 'Indirect Expenses',
            'type'          => 'expense',
            'is_system'     => true,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => ['trading', 'manufacturing', 'service', 'hybrid'],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'SUPP-001',
            'name'          => 'Office Supplies',
            'description'   => 'Office supplies and stationery',
            'group'         => 'Indirect Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'FUEL-EXP-001',
            'name'          => 'Diesel & Fuel Expense',
            'description'   => 'Diesel and fuel for generators and vehicles',
            'group'         => 'Indirect Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing'],
        ],
        [
            'code'          => 'GEN-MAINT-001',
            'name'          => 'Generator Maintenance',
            'description'   => 'Generator servicing and maintenance costs',
            'group'         => 'Indirect Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing'],
        ],
        [
            'code'          => 'SECURITY-EXP-001',
            'name'          => 'Security Services',
            'description'   => 'Security guard and surveillance services',
            'group'         => 'Indirect Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'REG-LEVY-001',
            'name'          => 'Regulatory Levies',
            'description'   => 'Government and regulatory levies (local/state)',
            'group'         => 'Indirect Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'hybrid'],
        ],
        [
            'code'          => 'COMPLIANCE-001',
            'name'          => 'Compliance & Filing Fees',
            'description'   => 'Statutory filings (CAC/NAFDAC/SON), permits and renewals',
            'group'         => 'Indirect Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'hybrid'],
        ],
        [
            'code'          => 'POS-CHG-001',
            'name'          => 'POS & Mobile Money Charges',
            'description'   => 'POS terminal fees and mobile money transaction charges',
            'group'         => 'Indirect Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading'],
        ],
        [
            'code'          => 'TRANS-001',
            'name'          => 'Transportation',
            'description'   => 'Transportation and travel expenses',
            'group'         => 'Indirect Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing'],
        ],
        [
            'code'          => 'PROF-001',
            'name'          => 'Professional Fees',
            'description'   => 'Legal, accounting, and professional fees',
            'group'         => 'Indirect Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['service', 'hybrid'],
        ],
        [
            'code'          => 'MARK-001',
            'name'          => 'Marketing & Advertising',
            'description'   => 'Marketing and advertising expenses',
            'group'         => 'Indirect Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'service', 'hybrid'],
        ],
        [
            'code'          => 'INS-001',
            'name'          => 'Insurance',
            'description'   => 'Insurance premiums',
            'group'         => 'Indirect Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'hybrid'],
        ],
        [
            'code'          => 'DEPR-001',
            'name'          => 'Depreciation Expense',
            'description'   => 'Depreciation on fixed assets',
            'group'         => 'Indirect Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'hybrid'],
        ],
        [
            'code'          => 'INT-EXP-001',
            'name'          => 'Interest Expense',
            'description'   => 'Interest paid on loans',
            'group'         => 'Indirect Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'MISC-001',
            'name'          => 'Miscellaneous Expense',
            'description'   => 'Other miscellaneous expenses',
            'group'         => 'Indirect Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'REPAIRS-MAINT-001',
            'name'          => 'Repairs & Maintenance',
            'description'   => 'Costs related to repairs and maintenance',
            'group'         => 'Indirect Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['manufacturing'],
        ],
        [
            'code'          => 'BAD-DEBTS-001',
            'name'          => 'Bad Debts',
            'description'   => 'Uncollectible accounts receivable',
            'group'         => 'Indirect Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'hybrid'],
        ],
        [
            'code'          => 'TRAVEL-ENT-001',
            'name'          => 'Travel & Entertainment',
            'description'   => 'Travel and entertainment expenses',
            'group'         => 'Indirect Expenses',
            'type'          => 'expense',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['service'],
        ],

        // ──────────────── CAPITAL ACCOUNT ───────────────────────
        [
            'code'          => 'CAPITAL-001',
            'name'          => 'Owner\'s Capital',
            'description'   => 'Owner\'s capital investment',
            'group'         => 'Capital Account',
            'type'          => 'equity',
            'is_system'     => true,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => ['trading', 'manufacturing', 'service', 'hybrid'],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'DRAW-001',
            'name'          => 'Owner\'s Drawings',
            'description'   => 'Owner\'s withdrawals',
            'group'         => 'Capital Account',
            'type'          => 'equity',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'RETAIN-001',
            'name'          => 'Retained Earnings',
            'description'   => 'Accumulated retained earnings',
            'group'         => 'Capital Account',
            'type'          => 'equity',
            'is_system'     => true,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => ['trading', 'manufacturing', 'service', 'hybrid'],
            'suggested_for' => ['trading', 'manufacturing', 'service', 'hybrid'],
        ],
        [
            'code'          => 'PARTNER-CAP-001',
            'name'          => 'Partner\'s Capital',
            'description'   => 'Capital contributed by partners',
            'group'         => 'Capital Account',
            'type'          => 'equity',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'SHAREHOLDER-EQ-001',
            'name'          => 'Shareholder\'s Equity',
            'description'   => 'Equity held by shareholders',
            'group'         => 'Capital Account',
            'type'          => 'equity',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
        [
            'code'          => 'DIVIDEND-RESERVE-001',
            'name'          => 'Dividend Reserve',
            'description'   => 'Reserve for future dividend payments',
            'group'         => 'Capital Account',
            'type'          => 'equity',
            'is_system'     => false,
            'categories'    => ['trading', 'manufacturing', 'service', 'hybrid'],
            'core_for'      => [],
            'suggested_for' => [],
        ],
    ];
}
